#! /bin/bash

cd /home/pi/git/RGPIODevice

echo Compiling java files...

javac  -classpath /home/pi/git/RGPIO/lib/'*' */*.java

echo Creating jar file...

jar cvfe RGPIODevice.jar rgpiodevice/RGPIODevice */*.class

echo Jar file in /home/pi/git/RGPIODevice
echo
ls -l /home/pi/git/RGPIODevice/RGPIODevice.jar
echo
