#! /bin/bash

if [  -n "$(pgrep -f  RGPIODevice)"  ]
then
echo RGPIO device is running, kill it first. Exiting...
exit
fi

java -cp /home/pi/RGPIODevice/RGPIODevice.jar:/home/pi/git/RGPIO/lib/'*' rgpiodevice/RGPIODevice




